import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Command,
  CreditCard,
  GitHub,
  HelpCircle,
  Loader,
  Moon,
  MoreVertical,
  Plus,
  Search,
  Settings,
  Activity,
  Star,
  Sun,
  Trash,
  User,
  X,
} from "react-feather";

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trash: Trash,
  search: Search,
  circle: Circle,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  star: Star,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: Sun,
  moon: Moon,
  check: Check,
  gitHub: GitHub,
  project: Activity,
};
